background {
    monitor =
    color = rgba(0d0d1aff)
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    outer_color = rgba(EF3946ee)
    inner_color = rgba(32111Cff)
    font_color = rgba(EF3946ff)
    fade_on_empty = true
    placeholder_text = <i>Password...</i>
    hide_input = false
    position = 0, -100
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$TIME"
    color = rgba(EF3946ff)
    font_size = 64
    font_family = JetBrainsMono Nerd Font
    position = 0, 100
    halign = center
    valign = center
}
