general {
    lock_cmd = hyprlock
    before_sleep_cmd = hyprlock
}

# Turn screen off after 5 minutes
listener {
    timeout = 300
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Lock screen after 5 minutes
listener {
    timeout = 300
    on-timeout = hyprlock
}

# Suspend after 10 minutes (only if samba not active)
listener {
    timeout = 600
    on-timeout = bash -c "if ! ss -tnp | grep -q smbd; then systemctl suspend; fi"
}
